#!/bin/bash
# ==============================================================================
# COURSE REFERENCE: RSLX EN-US SG M02 MANAGING LOG FILES (PART 2)
# DESCRIPTION: Reference script covering logging categories, severity levels, & files.
# USAGE: Read as a guide or run directly: bash rslx_m02_log_levels.sh
# ==============================================================================

clear
echo "=============================================================================="
echo "          RSLX M02 MANAGING LOG FILES: TYPES & SEVERITY REFERENCE"
echo "=============================================================================="

# ------------------------------------------------------------------------------
# 1. TYPES OF SYSTEM LOGGING
# ------------------------------------------------------------------------------
echo -e "\n--> 1. RECOGNIZED LOG CATEGORIES"
echo "• System Logs      : Track kernel initializations, startup information, and shutdowns."
echo "• Event Logs       : Record user security footprints, including login and logout events."
echo "• Application Logs : Document custom application startup times, actions, and program bugs."
echo "• Service Logs     : Track system services (e.g., web servers, database daemons)."


# ------------------------------------------------------------------------------
# 2. THE BUSINESS VALUE OF LOGGING
# ------------------------------------------------------------------------------
echo -e "\n--> 2. THE IMPORTANCE OF LOGGING"
echo "• Proactive Troubleshooting : Trace which application triggered an error or failure."
echo "• Security Audits           : Investigate who accessed a file, database, or server."
echo "• SLAs (Service-Level)      : Provides timestamps to prove troubleshooting response times."
echo "• Industry Requirements     : Satisfies legal compliance frameworks for data retention."


# ------------------------------------------------------------------------------
# 3. SPECIFIC APPLICATION LOG EXAMPLES
# ------------------------------------------------------------------------------
echo -e "\n--> 3. TARGETED LOG PATH EXAMPLES"
echo "• sudo cat /var/log/yum.log"
echo "  - Maintains records of all software installations, updates, and removals via YUM."
echo "• sudo cat /var/log/httpd/error_log"
echo "  - Tracks all errors, broken requests, and issues generated by the Apache Web Server."


# ------------------------------------------------------------------------------
# 4. LINUX SYSTEM SEVERITY LEVELS MATRIX
# ------------------------------------------------------------------------------
echo -e "\n--> 4. THE OFFICIAL LINUX SEVERITY LEVEL TABLE"
echo "=============================================================================="
echo " LEVEL | SEVERITY  | DESCRIPTION"
echo "=============================================================================="
echo "   0   | EMERGENCY | System is completely unstable or unusable."
echo "   1   | ALERT     | Immediate administrative action is required."
echo "   2   | CRITICAL  | Hard software/hardware errors; system may become unusable."
echo "   3   | ERROR     | Non-critical error conditions that still require attention."
echo "   4   | WARN      | Warning messages (Default log level on most distributions)."
echo "   5   | NOTICE    | Normal events but of significant or unusual importance."
echo "   6   | INFO      | Standard informational operational messages."
echo "   7   | DEBUG     | Verbose debugging messages used during development."
echo "=============================================================================="

echo -e "\nCRITICAL LOG THRESHOLD RULE:"
echo "• When a log level is configured, the system logs that level AND all levels ABOVE it."
echo "• Example: Setting level 4 (WARN) means levels 0, 1, 2, 3, and 4 are recorded."
echo "  Lower-severity messages (5-NOTICE, 6-INFO, 7-DEBUG) are filtered out and ignored."


# ------------------------------------------------------------------------------
# 5. DIAGNOSTIC SIMULATION BLOCK
# ------------------------------------------------------------------------------
echo -e "\n--> 5. LOG FILTERING COMMAND EXAMPLES"
echo "• Extract only level 0-3 critical errors from general system logs:"
echo "  sudo grep -E 'EMERGENCY|ALERT|CRITICAL|ERROR' /var/log/messages"

echo -e "\n=============================================================================="
echo "                              END OF REFERENCE"
echo "=============================================================================="
